### ISSUE TITLE
Inserting any URL in editor is being recognized as image

### ISSUE THREAD

**Issue by HeitorBRaymundo** [chenjuneking/quill-image-drop-and-paste#45]
`quill-image-drop-and-paste` version `1.2.11`
`quill` version `1.3.7`

When Im inserting a new URL from any website on my quill editor the plugin recognized it as image an then inserting this URL as `src` attribute inside an `img` tag.

![image](https://user-images.githubusercontent.com/18041471/198584092-53ce26fd-3840-4c64-8574-b2c99fbbd77e.png)
![image](https://user-images.githubusercontent.com/18041471/198584134-74f1d47b-93d2-4bc3-836f-d84e934e9b5f.png)

The problem is the function `urlIsImage` that are not handling with URL properly.
![image](https://user-images.githubusercontent.com/18041471/198584384-144fd6f4-eb48-4a66-b22e-c1ef4b2759da.png)

During the next weekend I'll try to open a PR to solve this issue, but if somebody knows some workaround to solve this, I'm all ears.

**Comment by HeitorBRaymundo** [comment]
@chenjuneking I saw this [commit](https://github.com/chenjuneking/quill-image-drop-and-paste/commit/10ce977cad975f1d92e200110307d735d17b1c7e) you made but I think thats does not solve the problem.

In the function `urlIsImage` the `url` is being inserting on `img.src = url`.

I updated to the new version `1.2.14` and the problem still ocurring: 
![image](https://user-images.githubusercontent.com/18041471/198588990-bfc0504c-d508-4554-9253-726e5e0e8770.png)

**Comment by chenjuneking** [comment]
Hi, @HeitorBRaymundo .
The url wouldn't be inserted into the editor as a image if the pasted url wasn't a valid image's url.
In order to know the pasted content was an image's url, we need to detect it. 
An image's url could be the format as `https://xxx.com/image.png`, that had the `.png` suffix could be easy to identify. Also, it could be the format as `https://xxx.com/13y47wsu237`, there was not any suffix, we are not able to know whether it's an image unless we read it.
That's why the http request sent, just for the image's url detect needed.

**Comment by HeitorBRaymundo** [comment]
@chenjuneking thanks for your explanation.
Last week I had a problem with CORS, the request was being blocked by our policies and then an error was throw, but I figured out that the version in our production env was `1.12.13` and then we upgraded to the version `1.12.14`.

Everything is fine, thanks once more.
